name: shopflow_mobile
description: Application mobile de gestion de stocks ShopFlow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  
  # Navigation
  go_router: ^14.0.0
  
  # State Management
  provider: ^6.1.1
  
  # API & Network
  http: ^1.2.0
  
  # Scanner de codes-barres
  mobile_scanner: ^5.1.1
  
  # Stockage local
  shared_preferences: ^2.2.2
  
  # PDF Generation
  pdf: ^3.10.8
  path_provider: ^2.1.3
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true